#!/usr/bin/env python3
"""
从开源数据集（/tmp/subway-utf8.txt, ZhuwenJ/subway 解码后）生成结构化站点 JS 数据.

输出: data/stations.generated.js  (export STATIONS_BY_LINE)
合并到 data/lines.js 时手动覆盖 STATIONS_BY_LINE 字段.
"""

import ast
import json
import re
import sys
from pathlib import Path

from pypinyin import lazy_pinyin, Style

ROOT = Path(__file__).resolve().parent.parent
SRC  = Path("/tmp/subway-utf8.txt")
OUT  = ROOT / "data" / "stations.generated.js"

# 数据集 line name → 我们的 line id
NAME_TO_ID = {
    "1号线":      "line1",
    "八通线":     "line1",       # 已贯通, 合并到 1 号线
    "2号线":      "line2",
    "4号线大兴线":"line4",
    "5号线":      "line5",
    "6号线":      "line6",
    "7号线":      "line7",
    "8号线北段":  "line8",
    "8号线南段":  "line8",
    "9号线":      "line9",
    "10号线":     "line10",
    "13号线":     "line13",
    "14号线东段": "line14",
    "14号线西段": "line14",
    "15号线":     "line15",
    "16号线":     "line16",
    "亦庄线":     "yz",
    "房山线":     "fs",
    "燕房线":     "yf",
    "S1线":       "s1",
    "昌平线":     "cp",
    "首都机场线": "airport",
    "西郊线":     "xj",
}

# 已知本站始发的站点 (来源: 北京地铁官网时刻表里以"始发站"标注的站)
KNOWN_ORIGIN = {
    "line1":  ["古城", "苹果园", "公主坟", "复兴门", "四惠", "四惠东", "环球度假区"],
    "line2":  ["西直门", "积水潭"],
    "line4":  ["天宫院", "公益西桥", "安河桥北"],
    "line5":  ["宋家庄", "天通苑北"],
    "line6":  ["潞城", "金安桥"],
    "line7":  ["焦化厂", "北京西站"],
    "line8":  ["朱辛庄", "瀛海", "南锣鼓巷"],
    "line9":  ["国家图书馆", "郭公庄"],
    "line10": ["巴沟", "宋家庄"],
    "line13": ["西直门", "东直门"],
    "line14": ["善各庄", "张郭庄"],
    "line15": ["俸伯", "清华东路西口"],
    "line16": ["北安河", "宛平城"],
    "yz":     ["宋家庄", "亦庄火车站"],
    "fs":     ["国家图书馆", "阎村东"],
    "yf":     ["阎村东", "燕山"],
    "s1":     ["石厂", "金安桥"],
    "cp":     ["昌平西山口", "蓟门桥"],
    "airport":["北新桥"],
    "xj":     ["香山", "巴沟"],
}

DIRECTIONS = {"东", "西", "南", "北", "中"}


def to_pinyin(cn: str) -> str:
    parts = lazy_pinyin(cn, style=Style.NORMAL)
    if not parts:
        return cn
    out = []
    buf = ""
    for ch, py in zip(cn, parts):
        if ch in DIRECTIONS and buf:
            out.append(buf.capitalize())
            out.append(py.capitalize())
            buf = ""
        else:
            buf += py
    if buf:
        out.append(buf.capitalize())
    return " ".join(out)


def parse_dataset(path: Path) -> list[dict]:
    """这是 JS 风格的单引号字面量, 用 ast.literal_eval 不行, 手动转引号."""
    text = path.read_text(encoding="utf-8")
    # 单引号 → 双引号 (粗暴, 但站名里没有引号)
    text = text.replace("'", '"')
    return json.loads(text)


def merge_lines(raw: list[dict]) -> dict[str, list[str]]:
    """处理数据集里 1号线/八通线、4号线大兴线、8号线北/南段、14号线东/西段 的合并."""
    by_id: dict[str, list[str]] = {}
    for entry in raw:
        line_name = entry["Line"]
        line_id = NAME_TO_ID.get(line_name)
        if not line_id:
            print(f"  ⚠ 未知线路: {line_name}, 跳过")
            continue
        stations = entry["Station"]

        if line_id == "line1" and line_name == "八通线":
            # 八通线接到 1 号线尾部, 去掉重叠站(四惠、四惠东在两份里都有)
            existing = by_id.get(line_id, [])
            existing_set = set(existing)
            for s in stations:
                if s not in existing_set:
                    existing.append(s)
                    existing_set.add(s)
            by_id[line_id] = existing
        elif line_id == "line8" and line_name == "8号线南段":
            # 南段接到北段, 中段重叠站(南锣鼓巷)
            existing = by_id.get(line_id, [])
            existing_set = set(existing)
            for s in stations:
                if s not in existing_set:
                    existing.append(s)
                    existing_set.add(s)
            by_id[line_id] = existing
        elif line_id == "line14" and line_name == "14号线西段":
            # 西段接东段
            existing = by_id.get(line_id, [])
            existing_set = set(existing)
            for s in stations:
                if s not in existing_set:
                    existing.append(s)
                    existing_set.add(s)
            by_id[line_id] = existing
        else:
            by_id[line_id] = list(dict.fromkeys(stations))  # 去重保序
    return by_id


def build_js(by_id: dict[str, list[str]]) -> str:
    out = [
        "// AUTO-GENERATED by scripts/build_stations.py — do not edit by hand",
        "// Source: ZhuwenJ/subway dataset (decoded gbk → utf-8)",
        "// Generated at: 2026-04-29",
        "",
        "const STATIONS_BY_LINE = {",
    ]
    for line_id, stations in by_id.items():
        origins = set(KNOWN_ORIGIN.get(line_id, []))
        out.append(f"  {line_id}: [")
        for idx, cn in enumerate(stations, start=1):
            py = to_pinyin(cn)
            tags = []
            if idx == 1:
                tags.append('endpoint: "west"')
            elif idx == len(stations):
                tags.append('endpoint: "east"')
            if cn in origins:
                tags.append("isOrigin: true")
            tag_str = (", " + ", ".join(tags)) if tags else ""
            out.append(f'    {{ idx: {idx:2d}, cn: "{cn}", py: "{py}"{tag_str} }},')
        out.append("  ],")
    out.append("};")
    out.append("")
    out.append("module.exports = { STATIONS_BY_LINE };")
    return "\n".join(out)


def main():
    if not SRC.exists():
        print(f"❌ 数据源不存在: {SRC}", file=sys.stderr)
        sys.exit(1)

    raw = parse_dataset(SRC)
    by_id = merge_lines(raw)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_js(by_id), encoding="utf-8")

    total = sum(len(v) for v in by_id.values())
    print(f"\n✅ 写入 {OUT.relative_to(ROOT)}")
    print(f"   线路数: {len(by_id)}")
    print(f"   站点数: {total}")
    for k, v in by_id.items():
        print(f"     · {k:8s} {len(v):3d} 站  ({v[0]} → {v[-1]})")


if __name__ == "__main__":
    main()
