#!/usr/bin/env python3
"""
从高德地图开放接口抓北京地铁全 27 条线路 + 站级首末班.

数据源:
  https://map.amap.com/service/subway?_=1&srhdata=1100_drw_beijing.json   线路结构 + 站点
  https://map.amap.com/service/subway?_=1&srhdata=1100_info_beijing.json  站点首末班

输出:
  data/stations.amap.generated.js          27 条线全站点 + 拼音
  data/timetable.amap.station.generated.js 站级真实首末班 + 合成班次 (工作日 + 双休)
  data/amap-timetables.json                原始首末班 (供检查)

依赖: requests
"""

import json
import re
import sys
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
OUT_STATIONS = ROOT / "data" / "stations.amap.generated.js"
OUT_TT_JSON  = ROOT / "data" / "amap-timetables.json"
OUT_TT_JS    = ROOT / "data" / "timetable.amap.station.generated.js"

DRW_URL  = "https://map.amap.com/service/subway?_=1&srhdata=1100_drw_beijing.json"
INFO_URL = "https://map.amap.com/service/subway?_=1&srhdata=1100_info_beijing.json"

LN_TO_ID = {
    "S1线":"s1", "1号线八通线":"line1", "2号线":"line2", "3号线":"line3",
    "4号线大兴线":"line4", "5号线":"line5", "6号线":"line6", "7号线":"line7",
    "8号线":"line8", "9号线":"line9", "10号线":"line10", "11号线":"line11",
    "12号线":"line12", "13号线":"line13", "14号线":"line14", "15号线":"line15",
    "16号线":"line16", "17号线":"line17", "18号线":"line18", "19号线":"line19",
    "昌平线":"cp", "大兴机场线":"dxap", "房山线":"fs", "首都机场线":"airport",
    "西郊线":"xj", "燕房线":"yf", "亦庄线":"yz",
}

LINE_COLORS = {
    "s1": "#A45A2A",      "line1": "#A4343A",  "line2": "#004B87", "line3": "#D90627",
    "line4": "#008C95",   "line5": "#AA0061",  "line6": "#B58500", "line7": "#FFC56E",
    "line8": "#009B77",   "line9": "#97D700",  "line10": "#0092BC","line11": "#FF8674",
    "line12": "#9C4F01",  "line13": "#F4DA40", "line14": "#CA9A8E","line15": "#653279",
    "line16": "#6BA539",  "line17": "#00ABAB", "line18": "#685BC7","line19": "#D3A3C9",
    "yz": "#D0006F",      "fs": "#D86018",     "yf": "#D86018",    "cp": "#D986BA",
    "airport": "#A192B2", "dxap": "#0049A5",   "xj": "#D22630",
}

PROFILE_WEEKDAY = [
    (5, 0, 7, 0, 5), (7, 0, 9, 30, 3), (9, 30, 17, 0, 5),
    (17, 0, 19, 30, 3), (19, 30, 21, 30, 5), (21, 30, 24, 0, 8),
]
PROFILE_WEEKEND = [
    (5, 0, 8, 0, 8), (8, 0, 10, 0, 7), (10, 0, 17, 0, 8),
    (17, 0, 20, 0, 7), (20, 0, 22, 0, 9), (22, 0, 24, 0, 10),
]


def interval_at(h, m, profile):
    cur = h * 60 + m
    for sh, sm, eh, em, iv in profile:
        if sh * 60 + sm <= cur < eh * 60 + em:
            return iv
    return 8


def parse_hhmm(s):
    if not s or s == "--:--":
        return None
    parts = s.split(":")
    if len(parts) != 2:
        return None
    try:
        return int(parts[0]), int(parts[1])
    except ValueError:
        return None


def normalize_pinyin(sp):
    if not sp:
        return ""
    sp = sp.strip()
    if " " in sp:
        return " ".join(p.capitalize() for p in sp.split())
    parts = re.findall(r"[A-Z][a-z]*", sp)
    return "".join(parts) if parts else sp.capitalize()


def gen_schedule(fh, fm, lh, lm, end_name="", end_color="", profile=None):
    p = profile or PROFILE_WEEKDAY
    sched = []
    h, m = fh, fm
    end_min = lh * 60 + lm
    while h * 60 + m <= end_min:
        entry = {"hour": h, "minute": m}
        if end_name:
            entry["end"] = end_name
        if end_color:
            entry["endColor"] = end_color
        sched.append(entry)
        iv = interval_at(h, m, p)
        m += iv
        while m >= 60:
            m -= 60; h += 1
        if h >= 30:
            break
    if sched:
        sched[-1]["hour"] = lh
        sched[-1]["minute"] = lm
    return sched


def build_station_directions(info):
    out = {}
    for line in info.get("l", []):
        for st in line.get("st", []):
            sid = st.get("si")
            if not sid:
                continue
            out.setdefault(sid, [])
            for d in st.get("d", []):
                next_sid = d.get("n")
                if not next_sid:
                    continue
                out[sid].append({
                    "ls": d.get("ls"),
                    "target": next_sid,
                    "ft": d.get("ft"),
                    "lt": d.get("lt"),
                })
    return out


def main():
    print("[1/2] 抓 drw...")
    drw = requests.get(DRW_URL, timeout=15).json()
    print(f"       {len(drw['l'])} 条线")

    print("[2/2] 抓 info...")
    info = requests.get(INFO_URL, timeout=15).json()

    # 站点 + line meta
    line_meta = {}
    js = [
        "// AUTO-GENERATED by scripts/fetch_amap.py",
        "// Source: map.amap.com/service/subway?srhdata=1100_drw_beijing.json",
        "",
        "const AMAP_STATIONS = {",
    ]
    for line in drw["l"]:
        ln = line.get("ln", "")
        line_id = LN_TO_ID.get(ln)
        if not line_id:
            continue
        li = (line.get("li") or "").split("|")
        line_meta[line_id] = {
            "ln": ln,
            "ls_a": li[0] if li else None,
            "ls_b": li[1] if len(li) > 1 else None,
            "stations": [],
        }
        stations = line.get("st", [])
        js.append(f"  {line_id}: [")
        for idx, s in enumerate(stations, 1):
            cn = s.get("n", "")
            sp = normalize_pinyin(s.get("sp", ""))
            sid = s.get("si") or s.get("sid")
            tags = []
            if idx == 1: tags.append('endpoint: "west"')
            elif idx == len(stations): tags.append('endpoint: "east"')
            ts = (", " + ", ".join(tags)) if tags else ""
            js.append(f'    {{ idx: {idx:2d}, cn: "{cn}", py: "{sp}"{ts} }},')
            line_meta[line_id]["stations"].append({"cn": cn, "sid": sid})
        js.append("  ],")
    js.append("};")
    js.append("")
    js.append("module.exports = { AMAP_STATIONS };")
    OUT_STATIONS.write_text("\n".join(js), encoding="utf-8")
    print(f"\n✅ 写入 {OUT_STATIONS.relative_to(ROOT)}")

    # 时刻表
    sid_to_recs = build_station_directions(info)
    timetables = {}
    raw = {}

    for line_id, meta in line_meta.items():
        stations = meta["stations"]
        ls_a, ls_b = meta["ls_a"], meta["ls_b"]
        west_end = stations[0]["cn"] if stations else ""
        east_end = stations[-1]["cn"] if stations else ""
        line_color = LINE_COLORS.get(line_id, "#888")

        timetables[line_id] = {}
        raw[line_id] = {"_amap_line_name": meta["ln"], "stations": {}}

        sids = [s["sid"] for s in stations]
        sid_to_idx = {sid: i for i, sid in enumerate(sids)}

        # 推断 ls → direction
        ls_dir_score = {ls_a: 0, ls_b: 0}
        for s in stations:
            i = sid_to_idx[s["sid"]]
            for r in sid_to_recs.get(s["sid"], []):
                if r["ls"] not in ls_dir_score or not r["ft"] or r["ft"] == "--:--":
                    continue
                tidx = sid_to_idx.get(r["target"])
                if tidx is None:
                    continue
                if tidx > i: ls_dir_score[r["ls"]] += 1
                elif tidx < i: ls_dir_score[r["ls"]] -= 1

        ls_to_dir = {}
        if ls_a and ls_b:
            if ls_dir_score[ls_a] >= ls_dir_score[ls_b]:
                ls_to_dir[ls_a], ls_to_dir[ls_b] = "east", "west"
            else:
                ls_to_dir[ls_a], ls_to_dir[ls_b] = "west", "east"
        elif ls_a:
            ls_to_dir[ls_a] = "east" if ls_dir_score[ls_a] >= 0 else "west"

        # 收集每站每方向
        for s in stations:
            cn, sid = s["cn"], s["sid"]
            timetables[line_id].setdefault(cn, {})
            raw[line_id]["stations"].setdefault(cn, {})
            for r in sid_to_recs.get(sid, []):
                direction = ls_to_dir.get(r["ls"])
                if not direction or not r["ft"] or r["ft"] == "--:--":
                    continue
                if direction in raw[line_id]["stations"][cn]:
                    continue
                raw[line_id]["stations"][cn][direction] = {"ft": r["ft"], "lt": r["lt"]}
                first = parse_hhmm(r["ft"])
                last = parse_hhmm(r["lt"])
                if first and last:
                    fh, fm = first; lh, lm = last
                    if (lh, lm) < (fh, fm): lh += 24
                    end_name = east_end if direction == "east" else west_end
                    timetables[line_id][cn][direction] = {
                        "weekday": gen_schedule(fh, fm, lh, lm, end_name, line_color, PROFILE_WEEKDAY),
                        "weekend": gen_schedule(fh, fm, lh, lm, end_name, line_color, PROFILE_WEEKEND),
                    }

    # 写 JS
    tt_js = [
        "// AUTO-GENERATED by scripts/fetch_amap.py",
        "// 高德 amap 站级真实首末班 + 工作日/双休 双合成节奏",
        "",
        "const _AMAP_SCHEDULES = " + json.dumps(timetables, ensure_ascii=False, indent=2) + ";",
        "",
        "function getAmapStationSchedule(lineId, stationCn, direction, daytype) {",
        "  const line = _AMAP_SCHEDULES[lineId];",
        "  if (!line) return null;",
        "  const station = line[stationCn];",
        "  if (!station) return null;",
        "  const dirData = station[direction];",
        "  if (!dirData) return null;",
        "  if (Array.isArray(dirData)) return dirData;",
        "  return dirData[daytype === 'weekend' ? 'weekend' : 'weekday'] || null;",
        "}",
        "",
        "module.exports = { getAmapStationSchedule, _AMAP_SCHEDULES };",
    ]
    OUT_TT_JS.write_text("\n".join(tt_js), encoding="utf-8")
    OUT_TT_JSON.write_text(json.dumps(raw, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"✅ 写入 {OUT_TT_JS.relative_to(ROOT)}")
    print(f"✅ 写入 {OUT_TT_JSON.relative_to(ROOT)}")
    total_st = sum(len(s) for s in timetables.values())
    print(f"\n   线路: {len(timetables)}, 站点: {total_st}")


if __name__ == "__main__":
    sys.exit(main())
